language: node_js
node_js:
- '6.11'
install: npm install
script: npm test
cache:
  directories:
  - node_modules
before_deploy:
- echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $TRAVIS_BRANCH"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(development|qa|production)$"
after_deploy: echo "Successfully executed deploy trigger for $TRAVIS_BRANCH"
env:
  global:
  - secure: nWY/mIpuCvdJsCO9GEtqkh6IHWbN2YyGVUZ54ux0apmwmATX6+SQNlw5KQ0de8UE60+jaoF/8ftT0ioEVbTbCOJtxwyRCGMrugCDW61AKosqLlZpW4UlJrtIX1FQIEYzO/RZC88DL2VEsnAPieM6Dw4COxURlh/pg3mObzHUFJE6XBRjfT1o1KgAMf2EK1Ta0XrcXzR5cWM38O+GIoqIYVeynQj4tq9YZ3qrH7BtNg1uL5Daw3qhCA3BVmReTixNr2sDncMKKUVYLWZ3mtIaCTIyO9TXqJvT5tAYGtBXjfDOplf6ubOoCLa4ZE4zJjGcxPX2Siyth5Wvs9G6St83HFCTRx8uhlXu8PKt4U0IVDe6ImFq5aWekfOSWskc+kFdnlB/xESN1ZUOVrKT6e3knKACWtoBBLLTUhZPQT/OIDrZRhgiuLyVLsZe6nAsxM1TB+wtO8JrutoRzyaN7VEWa17a419KjekpZXmH4hc1MZpBW2TnvKaeeaRlFLcSOHxJjG83Ba6Wlppl5fGyYkFR8awWZyLfFEHp6MevyladHD/nunyTLv41SP327ab+CGYojkJkwbsAhu428BsaW3IEvMoTqhy4XXRS31eBgs/wOd5fEwyijsatEGK4M0T25SpzqwYwDpw9mjWvFhhhW2sPTrAFsZ0pgTh6eC9Qz8rnHY0=
  - secure: cTzgGlDBE1QEor5hYLs7Ko1VfLG8v2zChfxHMY6ugrN+iACyayqC65vY3y8Td4JWZ75eB8dRC3GJflZxYu6QJMLPmhAkOOTxTsx31Ru5y1Un27NWoWjHJCG9CcYim8CwayYUiVlxBhdqvuAQN0PxGg82oGsRps9/EhT6TT0m0yCJx91h4ZDTXZ60gF8M/ZSBZDBpvca37CUAyrhunmt4i5hnfvYOA6iyh1NW6x1zaJlzbTSMxBM+vUbXEc2qxQDwawE6ODz/nZe+FsTScErLHBxDVkIk3sY4PzJYKbWiuYpTvz0MyimQQ2hlh4L+H+fOuWr0/1yohkc1Hj2BXPjyvJ5zTWOfF9zhNWcsEjHt+ZhimKiLl2CQztH74IdzPENX/3lqfAoXZfCMoDxilEWkaeRXA7KuRxCedgRC7HfdM6PfM+eBa77a8TOvRbRg9hsM2/7hqQsa7TQJiyruZq7rcl7zgpzJA7rxmQi6lBJVzqmOYmuRvgR2Y2Ou3tx84Cv1nSLKg+ZKBkRSxduD+6T4q4sLwYizTaPC/HLyYCPbE97MGv6luBbAC5PtzF1Cdi7FKUVPuwYlXi7d297a7VIdiq+qVZ/sxDJXVeEzQPrTXQpyI0i7h70YjzqsoQDkAONpPo7Lp7HRpeRo1iEceKl1x1fj86U16ycHeM3DemPI5Lc=
  - secure: sfZ5jmaxZfddSDS9SiRSZQtgPLd6NnTwfSOvJLhIuf5vNn97+Iue/P/LK1xuU+quNRl86jEF4q7NEr+b9sA4aTSnMsZhu8IelI/ODrJRkntp/IQsBTJcXnbBz9MHgscA1bpkXLfpcU1aNDLdLRVHlwBwh+jq2OG+zLhLO0nxSJ+QgP6dNeUBkuiSegJ2Aq9Ocxn8A7uT6BZACz69XlEZHm5UkFc9y4m93/8A8JuR3zkEul9d1FJSHc+gZWZBCSfTXs+NEakE0aawbd7IJAuca8LiC2aTOE2+QA5vhMC+HEl6cCg1WKOPLvRFfyWDLN5PNSfiuWsg2kwngiFkLLRx2k1mLkkrCg1OD3Kdg6DPXRAxba6Pkd9VEW2m9LX7K5FC8CAwiFfdGef0xWND7+VGNQE+5kVRAZ3wwetXmOhwd4q37KaQerR0EJKlzZzwavdTGSUvlXfD0LAZxy4Io6jOPtNqLB3YeXwPPJxoJ0UouzimyAKl+FZHx0pk97EAAQlUVlaIpHBavPCRaxLpwrm7NHyKk7dUGnK7MKXDDf/1X1ZCbtRIKNhVwP0KAptD2jS0S36sKm7atrFLNlkgTMyphEScRFA2k2hPU09XFu1mVwhTN+62UJ4e3fZBOdzD+15R/OIu8C/wAcCeaQCnpnloRpy6Oz30eXKLpq2lzT/Cs0E=
